export const typography = {
  fontFamily: {
    regular: "Inter-Regular",
    medium: "Inter-Medium",
    semiBold: "Inter-SemiBold",
    bold: "Inter-Bold",
    extraBold: "Inter-ExtraBold",
  },

  size: {
    overline: 11,
    caption: 12,
    labelS: 12,
    bodyS: 14,
    labelL: 14,
    bodyM: 15,
    bodyL: 16,
    title: 18,
    h2: 20,
    h1: 24,
    displayM: 28,
    displayL: 32,
    numericM: 20,
    numericXL: 28,
  },

  weight: {
    regular: "400",
    medium: "500",
    semiBold: "600",
    bold: "700",
    extraBold: "800",
  },

  lineHeight: {
    overline: 14,
    caption: 16,
    labelS: 16,
    bodyS: 20,
    labelL: 18,
    bodyM: 22,
    bodyL: 24,
    title: 24,
    h2: 26,
    h1: 30,
    displayM: 34,
    displayL: 38,
    numericM: 24,
    numericXL: 32,
  },
};
